/**
 * Format digest as a self-contained HTML viewer with RSVP Reader styling.
 */
export function formatHTML(digest, meta = {}) {
  const time = meta.timestamp || new Date().toISOString();
  const timeStr = new Date(time).toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' });
  const jsonData = JSON.stringify({
    id: slugify(digest.title) + '-' + Date.now().toString(36),
    title: digest.title,
    project: digest.project || '',
    time,
    blocks: digest.blocks,
  }, null, 2);

  const tagCounts = {};
  for (const b of digest.blocks) {
    tagCounts[b.tag] = (tagCounts[b.tag] || 0) + 1;
  }

  const tagsHTML = Object.entries(tagCounts).map(([tag, count]) => {
    const c = TAG_COLORS[tag];
    return `<span class="tag" style="background:${c.bg};color:${c.fg};border:1px solid ${c.border}">${c.label} &times;${count}</span>`;
  }).join(' ');

  const blocksHTML = digest.blocks.map(b => {
    const c = TAG_COLORS[b.tag];
    return `<div class="block">
      <span class="block-tag" style="color:${c.fg}">${c.label}</span>
      <span class="block-text">${esc(b.text)}</span>
    </div>`;
  }).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(digest.title)} - Claude Digest</title>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
  :root {
    --bg: #121010; --surface: #1e1b18; --border: #3a3530;
    --text: #e8e4df; --dim: #8a857e; --accent: #e84040;
  }
  .light {
    --bg: #faf8f5; --surface: #f0ede8; --border: #d5d0ca;
    --text: #1a1a1a; --dim: #7a756f; --accent: #e84040;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'DM Sans', sans-serif; background: var(--bg); color: var(--text); min-height: 100vh; padding: 40px 20px; transition: background 0.2s, color 0.2s; }
  .container { max-width: 680px; margin: 0 auto; }
  h1 { font-size: 28px; font-weight: 700; margin-bottom: 4px; }
  h1 span { color: var(--accent); }
  .meta { font-size: 13px; color: var(--dim); margin-bottom: 16px; }
  .tags { display: flex; gap: 8px; flex-wrap: wrap; margin-bottom: 20px; }
  .tag { font-size: 11px; font-weight: 600; padding: 3px 10px; border-radius: 12px; }
  .block { display: flex; gap: 10px; align-items: flex-start; padding: 10px 14px; border-bottom: 1px solid var(--border); }
  .block:last-child { border-bottom: none; }
  .block-tag { font-weight: 700; font-size: 11px; min-width: 60px; padding-top: 2px; flex-shrink: 0; }
  .block-text { font-size: 14px; line-height: 1.6; color: var(--text); opacity: 0.9; }
  .blocks-container { background: var(--surface); border: 1px solid var(--border); border-radius: 10px; overflow: hidden; margin-bottom: 20px; }
  .actions { display: flex; gap: 8px; margin-bottom: 20px; }
  button { font-family: 'DM Sans', sans-serif; cursor: pointer; border: 1px solid var(--border); background: var(--surface); color: var(--text); border-radius: 8px; padding: 8px 16px; font-size: 13px; font-weight: 500; transition: all 0.15s; }
  button:hover { border-color: var(--accent); }
  .theme-btn { position: fixed; top: 16px; right: 16px; border-radius: 50%; width: 36px; height: 36px; padding: 0; font-size: 14px; display: flex; align-items: center; justify-content: center; }
  pre { background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 14px; font-size: 12px; overflow-x: auto; color: var(--dim); display: none; margin-bottom: 20px; }
  pre.visible { display: block; }
  .footer { font-size: 11px; color: var(--dim); opacity: 0.5; text-align: center; margin-top: 40px; }
</style>
</head>
<body>
<button class="theme-btn" onclick="document.body.classList.toggle('light');this.textContent=document.body.classList.contains('light')?'\\u25CF':'\\u2600'">\\u2600</button>
<div class="container">
  <h1><span>D</span>igest</h1>
  <div class="meta">${esc(digest.project || 'Unknown Project')} &mdash; ${esc(timeStr)}</div>
  <div class="tags">${tagsHTML}</div>
  <div class="blocks-container">${blocksHTML}</div>
  <div class="actions">
    <button onclick="copyJSON()">Copy JSON</button>
    <button onclick="toggleRaw()">View Raw JSON</button>
  </div>
  <pre id="rawJson">${esc(jsonData)}</pre>
  <div class="footer">Generated by claude-digest</div>
</div>
<script>
function copyJSON(){navigator.clipboard.writeText(${JSON.stringify(jsonData)}).then(()=>{event.target.textContent='Copied!';setTimeout(()=>event.target.textContent='Copy JSON',1500)})}
function toggleRaw(){document.getElementById('rawJson').classList.toggle('visible')}
</script>
</body>
</html>`;
}

const TAG_COLORS = {
  critical: { bg: '#e8404020', fg: '#e84040', border: '#e8404060', label: 'CRITICAL' },
  high:     { bg: '#e8840020', fg: '#e88400', border: '#e8840060', label: 'HIGH' },
  done:     { bg: '#40b86020', fg: '#40b860', border: '#40b86060', label: 'DONE' },
  info:     { bg: '#4088e820', fg: '#4088e8', border: '#4088e860', label: 'INFO' },
  decision: { bg: '#a855f720', fg: '#a855f7', border: '#a855f760', label: 'DECIDE' },
};

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function slugify(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 50);
}
