const TAG_EMOJI = {
  critical: '\u{1F534}',  // red circle
  high:     '\u{1F7E0}',  // orange circle
  done:     '\u{1F7E2}',  // green circle
  info:     '\u{1F535}',  // blue circle
  decision: '\u{1F7E3}',  // purple circle
};

const TAG_LABEL = {
  critical: 'CRITICAL',
  high: 'HIGH',
  done: 'DONE',
  info: 'INFO',
  decision: 'DECISION',
};

/**
 * Format digest as readable Markdown.
 */
export function formatMarkdown(digest, meta = {}) {
  const time = meta.timestamp
    ? new Date(meta.timestamp).toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' })
    : new Date().toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' });

  const lines = [
    `# ${digest.title}`,
    `*${digest.project || 'Unknown Project'} \u2014 ${time}*`,
    '',
  ];

  for (const block of digest.blocks) {
    const emoji = TAG_EMOJI[block.tag] || '\u26AA';
    const label = TAG_LABEL[block.tag] || block.tag.toUpperCase();
    lines.push(`${emoji} **${label}** ${block.text}`);
  }

  lines.push('');
  lines.push(`---`);
  lines.push(`*Generated by claude-digest*`);

  return lines.join('\n');
}
